# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainUI.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1000, 580)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 580))
        MainWindow.setMaximumSize(QtCore.QSize(1000, 580))
        MainWindow.setAcceptDrops(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/proPrefix/image/spider.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.Chinese, QtCore.QLocale.China))
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.spiderView = QtWidgets.QTableView(self.centralwidget)
        self.spiderView.setGeometry(QtCore.QRect(10, 10, 621, 481))
        self.spiderView.setObjectName("spiderView")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(650, 240, 351, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(680, 300, 261, 125))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.addTaskGridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.addTaskGridLayout.setContentsMargins(5, 5, 5, 5)
        self.addTaskGridLayout.setVerticalSpacing(10)
        self.addTaskGridLayout.setObjectName("addTaskGridLayout")
        self.addTaskButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.addTaskButton.setEnabled(False)
        self.addTaskButton.setObjectName("addTaskButton")
        self.addTaskGridLayout.addWidget(self.addTaskButton, 4, 1, 1, 1)
        self.endTimeEdit = QtWidgets.QDateTimeEdit(self.gridLayoutWidget)
        self.endTimeEdit.setObjectName("endTimeEdit")
        self.addTaskGridLayout.addWidget(self.endTimeEdit, 3, 0, 1, 2)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_12.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.addTaskGridLayout.addWidget(self.label_12, 1, 0, 1, 1)
        self.startTimeEdit = QtWidgets.QDateTimeEdit(self.gridLayoutWidget)
        self.startTimeEdit.setObjectName("startTimeEdit")
        self.addTaskGridLayout.addWidget(self.startTimeEdit, 0, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.addTaskGridLayout.addItem(spacerItem, 4, 0, 1, 1)
        self.monitorLabel = QtWidgets.QLabel(self.centralwidget)
        self.monitorLabel.setGeometry(QtCore.QRect(660, 10, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.monitorLabel.setFont(font)
        self.monitorLabel.setAutoFillBackground(False)
        self.monitorLabel.setObjectName("monitorLabel")
        self.addTaskLabel = QtWidgets.QLabel(self.centralwidget)
        self.addTaskLabel.setGeometry(QtCore.QRect(660, 260, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.addTaskLabel.setFont(font)
        self.addTaskLabel.setAutoFillBackground(False)
        self.addTaskLabel.setObjectName("addTaskLabel")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(636, 0, 20, 551))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(650, 440, 351, 20))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(650, 50, 321, 181))
        self.layoutWidget.setObjectName("layoutWidget")
        self.monitorGridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.monitorGridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.monitorGridLayout.setContentsMargins(0, 0, 0, 0)
        self.monitorGridLayout.setSpacing(0)
        self.monitorGridLayout.setObjectName("monitorGridLayout")
        self.loginStatusLED = QtWidgets.QLabel(self.layoutWidget)
        self.loginStatusLED.setMaximumSize(QtCore.QSize(18, 18))
        self.loginStatusLED.setStyleSheet("image:url(:/proPrefix/image/led_unknow.png)")
        self.loginStatusLED.setText("")
        self.loginStatusLED.setObjectName("loginStatusLED")
        self.monitorGridLayout.addWidget(self.loginStatusLED, 4, 3, 1, 1)
        self.line = QtWidgets.QFrame(self.layoutWidget)
        self.line.setLineWidth(1)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.monitorGridLayout.addWidget(self.line, 1, 0, 1, 4)
        self.dataStatusLED = QtWidgets.QLabel(self.layoutWidget)
        self.dataStatusLED.setMaximumSize(QtCore.QSize(18, 18))
        self.dataStatusLED.setStyleSheet("image:url(:/proPrefix/image/led_unknow.png)")
        self.dataStatusLED.setText("")
        self.dataStatusLED.setObjectName("dataStatusLED")
        self.monitorGridLayout.addWidget(self.dataStatusLED, 5, 3, 1, 1)
        self.dataStatusLabel = QtWidgets.QLabel(self.layoutWidget)
        self.dataStatusLabel.setObjectName("dataStatusLabel")
        self.monitorGridLayout.addWidget(self.dataStatusLabel, 5, 2, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.layoutWidget)
        self.line_2.setLineWidth(1)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.monitorGridLayout.addWidget(self.line_2, 3, 0, 1, 4)
        self.spiderStatusLabel = QtWidgets.QLabel(self.layoutWidget)
        self.spiderStatusLabel.setObjectName("spiderStatusLabel")
        self.monitorGridLayout.addWidget(self.spiderStatusLabel, 4, 0, 2, 1)
        self.webStatusLabel = QtWidgets.QLabel(self.layoutWidget)
        self.webStatusLabel.setObjectName("webStatusLabel")
        self.monitorGridLayout.addWidget(self.webStatusLabel, 2, 0, 1, 1)
        self.dbStatusLabel = QtWidgets.QLabel(self.layoutWidget)
        self.dbStatusLabel.setObjectName("dbStatusLabel")
        self.monitorGridLayout.addWidget(self.dbStatusLabel, 0, 0, 1, 1)
        self.loginStatusLabel = QtWidgets.QLabel(self.layoutWidget)
        self.loginStatusLabel.setObjectName("loginStatusLabel")
        self.monitorGridLayout.addWidget(self.loginStatusLabel, 4, 2, 1, 1)
        self.webStatusLED = QtWidgets.QLabel(self.layoutWidget)
        self.webStatusLED.setMinimumSize(QtCore.QSize(0, 0))
        self.webStatusLED.setMaximumSize(QtCore.QSize(18, 18))
        self.webStatusLED.setStyleSheet("image:url(:/proPrefix/image/led_unknow.png)")
        self.webStatusLED.setText("")
        self.webStatusLED.setScaledContents(False)
        self.webStatusLED.setObjectName("webStatusLED")
        self.monitorGridLayout.addWidget(self.webStatusLED, 2, 1, 1, 1)
        self.dbStatusLED = QtWidgets.QLabel(self.layoutWidget)
        self.dbStatusLED.setMaximumSize(QtCore.QSize(18, 18))
        self.dbStatusLED.setStyleSheet("image:url(:/proPrefix/image/led_unknow.png)")
        self.dbStatusLED.setText("")
        self.dbStatusLED.setObjectName("dbStatusLED")
        self.monitorGridLayout.addWidget(self.dbStatusLED, 0, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("等线 Light")
        font.setPointSize(26)
        self.label_10.setFont(font)
        self.label_10.setScaledContents(True)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setWordWrap(False)
        self.label_10.setIndent(-1)
        self.label_10.setObjectName("label_10")
        self.monitorGridLayout.addWidget(self.label_10, 4, 1, 2, 1)
        self.monitorGridLayout.setColumnMinimumWidth(0, 1)
        self.monitorGridLayout.setColumnMinimumWidth(2, 1)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(670, 470, 311, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.progressBar = QtWidgets.QProgressBar(self.horizontalLayoutWidget)
        self.progressBar.setEnabled(False)
        self.progressBar.setProperty("value", 50)
        self.progressBar.setTextVisible(False)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout.addWidget(self.progressBar)
        self.startEndButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.startEndButton.setMinimumSize(QtCore.QSize(93, 0))
        self.startEndButton.setMaximumSize(QtCore.QSize(93, 28))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.startEndButton.setFont(font)
        self.startEndButton.setObjectName("startEndButton")
        self.horizontalLayout.addWidget(self.startEndButton)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 490, 644, 38))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_3.setContentsMargins(2, 5, 2, 5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.firstPageButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.firstPageButton.setObjectName("firstPageButton")
        self.horizontalLayout_3.addWidget(self.firstPageButton)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.prePageButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.prePageButton.setObjectName("prePageButton")
        self.horizontalLayout_3.addWidget(self.prePageButton)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.numberPageInput = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.numberPageInput.setEnabled(True)
        self.numberPageInput.setMinimumSize(QtCore.QSize(40, 0))
        self.numberPageInput.setMaximumSize(QtCore.QSize(40, 16777215))
        self.numberPageInput.setAlignment(QtCore.Qt.AlignCenter)
        self.numberPageInput.setObjectName("numberPageInput")
        self.horizontalLayout_3.addWidget(self.numberPageInput)
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.goPageButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.goPageButton.setMinimumSize(QtCore.QSize(40, 0))
        self.goPageButton.setMaximumSize(QtCore.QSize(40, 16777215))
        self.goPageButton.setObjectName("goPageButton")
        self.horizontalLayout_3.addWidget(self.goPageButton)
        self.totalPageLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.totalPageLabel.setMinimumSize(QtCore.QSize(60, 0))
        self.totalPageLabel.setMaximumSize(QtCore.QSize(60, 16777215))
        self.totalPageLabel.setTextFormat(QtCore.Qt.PlainText)
        self.totalPageLabel.setObjectName("totalPageLabel")
        self.horizontalLayout_3.addWidget(self.totalPageLabel)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.nextPageButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.nextPageButton.setAutoDefault(False)
        self.nextPageButton.setObjectName("nextPageButton")
        self.horizontalLayout_3.addWidget(self.nextPageButton)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.lastPageButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.lastPageButton.setObjectName("lastPageButton")
        self.horizontalLayout_3.addWidget(self.lastPageButton)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 26))
        self.menubar.setObjectName("menubar")
        self.settings = QtWidgets.QMenu(self.menubar)
        self.settings.setObjectName("settings")
        self.about = QtWidgets.QMenu(self.menubar)
        self.about.setObjectName("about")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.server_setting = QtWidgets.QAction(MainWindow)
        self.server_setting.setCheckable(False)
        self.server_setting.setShortcutVisibleInContextMenu(True)
        self.server_setting.setObjectName("server_setting")
        self.web_setting = QtWidgets.QAction(MainWindow)
        self.web_setting.setShortcutVisibleInContextMenu(True)
        self.web_setting.setObjectName("web_setting")
        self.about_energy_platform_spider = QtWidgets.QAction(MainWindow)
        self.about_energy_platform_spider.setIcon(icon)
        self.about_energy_platform_spider.setObjectName("about_energy_platform_spider")
        self.about_pyqt5 = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/proPrefix/image/Qt_logo_2016.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.about_pyqt5.setIcon(icon1)
        self.about_pyqt5.setObjectName("about_pyqt5")
        self.proxy_setting = QtWidgets.QAction(MainWindow)
        self.proxy_setting.setShortcutVisibleInContextMenu(True)
        self.proxy_setting.setObjectName("proxy_setting")
        self.settings.addAction(self.server_setting)
        self.settings.addAction(self.web_setting)
        self.settings.addAction(self.proxy_setting)
        self.about.addAction(self.about_energy_platform_spider)
        self.about.addAction(self.about_pyqt5)
        self.menubar.addAction(self.settings.menuAction())
        self.menubar.addAction(self.about.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.spiderView, self.startTimeEdit)
        MainWindow.setTabOrder(self.startTimeEdit, self.endTimeEdit)
        MainWindow.setTabOrder(self.endTimeEdit, self.addTaskButton)
        MainWindow.setTabOrder(self.addTaskButton, self.startEndButton)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "机电事业部能源数据爬取软件"))
        self.addTaskButton.setText(_translate("MainWindow", "添加"))
        self.endTimeEdit.setDisplayFormat(_translate("MainWindow", "yyyy-M-d h:mm"))
        self.label_12.setText(_translate("MainWindow", "至"))
        self.startTimeEdit.setDisplayFormat(_translate("MainWindow", "yyyy-M-d h:mm"))
        self.monitorLabel.setText(_translate("MainWindow", "状态监控"))
        self.addTaskLabel.setText(_translate("MainWindow", "添加任务"))
        self.dataStatusLabel.setText(_translate("MainWindow", "目录数据状态："))
        self.spiderStatusLabel.setText(_translate("MainWindow", "爬虫状态："))
        self.webStatusLabel.setText(_translate("MainWindow", "网页状态："))
        self.dbStatusLabel.setText(_translate("MainWindow", "数据库状态："))
        self.loginStatusLabel.setText(_translate("MainWindow", "用户登录状态："))
        self.label_10.setText(_translate("MainWindow", "{"))
        self.startEndButton.setText(_translate("MainWindow", "启动爬虫"))
        self.firstPageButton.setText(_translate("MainWindow", "首页"))
        self.prePageButton.setText(_translate("MainWindow", "上页"))
        self.label.setText(_translate("MainWindow", "第"))
        self.numberPageInput.setText(_translate("MainWindow", "0"))
        self.label_2.setText(_translate("MainWindow", "页"))
        self.goPageButton.setText(_translate("MainWindow", "跳转"))
        self.totalPageLabel.setText(_translate("MainWindow", "共100页"))
        self.nextPageButton.setText(_translate("MainWindow", "下页"))
        self.lastPageButton.setText(_translate("MainWindow", "末页"))
        self.settings.setTitle(_translate("MainWindow", "设置"))
        self.about.setTitle(_translate("MainWindow", "关于"))
        self.server_setting.setText(_translate("MainWindow", "数据库参数"))
        self.server_setting.setShortcut(_translate("MainWindow", "Shift+S"))
        self.web_setting.setText(_translate("MainWindow", "网页参数"))
        self.web_setting.setShortcut(_translate("MainWindow", "Shift+W"))
        self.about_energy_platform_spider.setText(_translate("MainWindow", "项目"))
        self.about_pyqt5.setText(_translate("MainWindow", "pyqt5"))
        self.about_pyqt5.setIconText(_translate("MainWindow", "pyqt5"))
        self.proxy_setting.setText(_translate("MainWindow", "网络代理"))
        self.proxy_setting.setShortcut(_translate("MainWindow", "Shift+P"))

import ResFiles_rc
