# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'server_setting.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_dialog(object):
    def setupUi(self, dialog):
        dialog.setObjectName("dialog")
        dialog.resize(400, 330)
        dialog.setMinimumSize(QtCore.QSize(400, 330))
        dialog.setMaximumSize(QtCore.QSize(400, 400))
        dialog.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        dialog.setInputMethodHints(QtCore.Qt.ImhNone)
        dialog.setSizeGripEnabled(False)
        dialog.setModal(False)
        self.cancel = QtWidgets.QPushButton(dialog)
        self.cancel.setGeometry(QtCore.QRect(300, 290, 93, 28))
        self.cancel.setObjectName("cancel")
        self.OK = QtWidgets.QPushButton(dialog)
        self.OK.setGeometry(QtCore.QRect(200, 290, 93, 28))
        self.OK.setMouseTracking(True)
        self.OK.setAutoFillBackground(False)
        self.OK.setStyleSheet("")
        self.OK.setCheckable(False)
        self.OK.setDefault(True)
        self.OK.setFlat(False)
        self.OK.setObjectName("OK")
        self.verticalLayoutWidget = QtWidgets.QWidget(dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 381, 261))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.server_msg = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.server_msg.setContentsMargins(0, 0, 0, 0)
        self.server_msg.setObjectName("server_msg")
        self.host_port_sid = QtWidgets.QGridLayout()
        self.host_port_sid.setObjectName("host_port_sid")
        self.port_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.port_label.setObjectName("port_label")
        self.host_port_sid.addWidget(self.port_label, 0, 3, 1, 1)
        self.port_input = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.port_input.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.port_input.sizePolicy().hasHeightForWidth())
        self.port_input.setSizePolicy(sizePolicy)
        self.port_input.setMinimumSize(QtCore.QSize(5, 0))
        self.port_input.setMaximumSize(QtCore.QSize(50, 16777215))
        self.port_input.setText("")
        self.port_input.setObjectName("port_input")
        self.host_port_sid.addWidget(self.port_input, 0, 4, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(60, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.host_port_sid.addItem(spacerItem, 1, 0, 1, 1)
        self.host_input = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.host_input.setObjectName("host_input")
        self.host_port_sid.addWidget(self.host_input, 0, 1, 1, 1)
        self.sid_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.sid_label.setObjectName("sid_label")
        self.host_port_sid.addWidget(self.sid_label, 2, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.host_port_sid.addItem(spacerItem1, 2, 2, 1, 1)
        self.sid_input = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.sid_input.setObjectName("sid_input")
        self.host_port_sid.addWidget(self.sid_input, 2, 1, 1, 1)
        self.host_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.host_label.setObjectName("host_label")
        self.host_port_sid.addWidget(self.host_label, 0, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.host_port_sid.addItem(spacerItem2, 0, 2, 1, 1)
        self.server_msg.addLayout(self.host_port_sid)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.server_msg.addItem(spacerItem3)
        self.user_pwd = QtWidgets.QGridLayout()
        self.user_pwd.setObjectName("user_pwd")
        self.user_input = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.user_input.setObjectName("user_input")
        self.user_pwd.addWidget(self.user_input, 0, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.user_pwd.addItem(spacerItem4, 0, 3, 1, 1)
        self.user_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.user_label.setObjectName("user_label")
        self.user_pwd.addWidget(self.user_label, 0, 0, 1, 1)
        self.pwd_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.pwd_label.setObjectName("pwd_label")
        self.user_pwd.addWidget(self.pwd_label, 2, 0, 1, 1)
        self.visible_check = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.visible_check.setObjectName("visible_check")
        self.user_pwd.addWidget(self.visible_check, 2, 3, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(60, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.user_pwd.addItem(spacerItem5, 1, 0, 1, 1)
        self.pwd_input = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.pwd_input.setText("")
        self.pwd_input.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pwd_input.setObjectName("pwd_input")
        self.user_pwd.addWidget(self.pwd_input, 2, 1, 1, 1)
        self.server_msg.addLayout(self.user_pwd)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.server_msg.addItem(spacerItem6)
        self.URL = QtWidgets.QGridLayout()
        self.URL.setObjectName("URL")
        self.URL_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.URL_label.setMinimumSize(QtCore.QSize(60, 0))
        self.URL_label.setMaximumSize(QtCore.QSize(60, 16777215))
        self.URL_label.setObjectName("URL_label")
        self.URL.addWidget(self.URL_label, 0, 0, 1, 1)
        self.URL_input = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.URL_input.setEnabled(True)
        self.URL_input.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.URL_input.setAutoFillBackground(False)
        self.URL_input.setStyleSheet("background: transparent;")
        self.URL_input.setInputMask("")
        self.URL_input.setFrame(True)
        self.URL_input.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.URL_input.setCursorPosition(0)
        self.URL_input.setDragEnabled(False)
        self.URL_input.setReadOnly(True)
        self.URL_input.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.URL_input.setObjectName("URL_input")
        self.URL.addWidget(self.URL_input, 0, 1, 1, 1)
        self.server_msg.addLayout(self.URL)
        self.test = QtWidgets.QHBoxLayout()
        self.test.setObjectName("test")
        spacerItem7 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.test.addItem(spacerItem7)
        self.test_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.test_button.setObjectName("test_button")
        self.test.addWidget(self.test_button)
        spacerItem8 = QtWidgets.QSpacerItem(180, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.test.addItem(spacerItem8)
        self.server_msg.addLayout(self.test)

        self.retranslateUi(dialog)
        self.cancel.clicked.connect(dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(dialog)
        dialog.setTabOrder(self.host_input, self.port_input)
        dialog.setTabOrder(self.port_input, self.sid_input)
        dialog.setTabOrder(self.sid_input, self.user_input)
        dialog.setTabOrder(self.user_input, self.pwd_input)
        dialog.setTabOrder(self.pwd_input, self.visible_check)
        dialog.setTabOrder(self.visible_check, self.URL_input)
        dialog.setTabOrder(self.URL_input, self.test_button)
        dialog.setTabOrder(self.test_button, self.OK)
        dialog.setTabOrder(self.OK, self.cancel)

    def retranslateUi(self, dialog):
        _translate = QtCore.QCoreApplication.translate
        dialog.setWindowTitle(_translate("dialog", "数据库参数设置"))
        self.cancel.setText(_translate("dialog", "取消"))
        self.OK.setText(_translate("dialog", "确认"))
        self.port_label.setText(_translate("dialog", "端口:"))
        self.port_input.setPlaceholderText(_translate("dialog", "1521"))
        self.host_input.setPlaceholderText(_translate("dialog", "localhost"))
        self.sid_label.setText(_translate("dialog", "SID:"))
        self.host_label.setText(_translate("dialog", "主机:"))
        self.user_label.setText(_translate("dialog", "用户名："))
        self.pwd_label.setText(_translate("dialog", "密码："))
        self.visible_check.setText(_translate("dialog", "可见"))
        self.URL_label.setText(_translate("dialog", "URL:"))
        self.URL_input.setPlaceholderText(_translate("dialog", "用户名/密码@主机号:端口/SID"))
        self.test_button.setText(_translate("dialog", "测试连接"))

